<?php
// A better version of ucwords that capitalizes just the first word, regardless 
// of the previous case. It also capitalizes the first word after an array of delimiters.
// @$string - the string to be capitalized
// @$delimiters  (optional) - an array of characters that should be followed by a capital letter
// This function accomplishes a similar task to ucwords(strtolower("Some string"))
function impact_util_capwords($string, $delimiters = array('-','/','(', ' ')) {
  $string = strtolower($string);
  foreach ($delimiters as $delim) {
    $string = explode($delim, $string);
    foreach ($string as $index=>$capword) {
      $string[$index] = ucfirst($capword);
    }
    $string = implode($delim, $string);
  }
  return $string;
}

// Get the current user's fscs key
function impact_util_fscs() {
  return token_replace('[current-user:profile-library-registration:field-library-reg-system]');
}
// Determine weather the current user's profile (imls or intake) is submitted or not
function impact_util_profile_status($type) {
  global $user;
  $sql = "SELECT pid FROM {myimpact_profile_status} WHERE type = '$type' AND uid = '$user->uid'";
  return db_query($sql)->fetchField();
}
// Determine whether the current user's profile (imls or intake) is saved or not
function impact_util_profile_save($type) {
  global $user;
  $sql = "SELECT pid FROM {profile} WHERE type = '$type' AND uid = '$user->uid'";
  return db_query($sql)->fetchField();
}
// Determine which step in a form the user is on
function impact_util_form_step() {
  $url = explode('/', current_path());
  return $url[count($url)-1];
}
// Determine which user a form is for based on the url
function impact_util_user_url() {
  $url = explode('/', current_path());
  return $url[count($url)-2];
}
// Url to return a user to view page
function impact_util_profile_view_url() {
  global $base_url;
  $url = explode('/', current_path());
  return $base_url . '/' . $url[count($url)-3] . '/' . $url[count($url)-2];
}
// Check if The library is administering paper surveys
// Returns 1 if yes, 0 if no
function impact_util_paper_survey() {
  global $user;
  $paper = impact_util_profile_save('survey_fielding');
  if($paper) {
    $sql = "SELECT field_paper_survey_value FROM {field_data_field_paper_survey} WHERE entity_id = '$paper'";
    return db_query($sql)->fetchField();
  } else
    return 0;
}
function impact_util_paper_survey_finished() {
  global $user;
  $sql = "SELECT paper_survey_finished FROM {paper_survey_finished} WHERE uid = $user->uid";
  return db_query($sql)->fetchField();
}
// Get the current library's state
function impact_util_get_state() {
  return token_replace('[current-user:profile-library-registration:field-library-reg-state]');
}