<?php
// A better version of ucwords that capitalizes just the first word, regardless 
// of the previous case. It also capitalizes the first word after an array of delimiters.
// @$string - the string to be capitalized
// @$delimiters  (optional) - an array of characters that should be followed by a capital letter
// This function accomplishes a similar task to ucwords(strtolower("Some string"))
function impact_util_capwords($string, $delimiters = array('-','/','(', ' ')) {
  $string = strtolower($string);
  foreach ($delimiters as $delim) {
    $string = explode($delim, $string);
    foreach ($string as $index=>$capword) {
      $string[$index] = ucfirst($capword);
    }
    $string = implode($delim, $string);
  }
  return $string;
}

// Get the current user's fscs key
function impact_util_fscs() {
  return token_replace('[current-user:profile-library-registration:field-library-reg-system]');
}
// Determine weather the current user's profile (imls or intake) is submitted or not
function impact_util_profile_status($type) {
  global $user;
  $sql = "SELECT pid FROM {myimpact_profile_status} WHERE type = '$type' AND uid = '$user->uid'";
  return db_query($sql)->fetchField();
}
// Determine whether the current user's profile (imls or intake) is saved or not
function impact_util_profile_save($type) {
  global $user;
  $sql = "SELECT pid FROM {profile} WHERE type = '$type' AND uid = '$user->uid'";
  return db_query($sql)->fetchField();
}