<?php
function imls_data_form_profile2_edit_pilot_intake_form_alter(&$form, &$form_state) {
  drupal_set_title('Intake Form');
  if(impact_util_profile_status('pilot_intake')) {
    drupal_set_message('You have already submitted this form. Please contact us if you need to make a change.', 'warning');
    drupal_goto(impact_util_profile_view_url());
  }
}
function intake_form_profile2_view($profile, $view_mode, $langcode) {
  if($profile->type == 'pilot_intake'){
    // If the profile is unsubmitted (and not on confirm), go to edit
    if(isset($profile->content['empty'])
    || !impact_util_profile_status('pilot_intake')
    && impact_util_form_step() != 'confirm') 
      drupal_goto(current_path() . '/edit');
      
    drupal_set_title('Intake Form');
    // Get all the field info for the pilot_intake profile
    $query = "SELECT field_name, data FROM {field_config_instance} WHERE bundle = 'pilot_intake'";
    $fields = db_query($query)->fetchAllKeyed();
    
    $header = array('Field', 'Data');
    $attributes = array('class' => array('library_form'));
    $rows = array();
    foreach($profile->content as $field => $value) {
      $splode = explode('_', $field);
      if($splode[0] == 'field') {
        $weight = unserialize($fields[$field]);
        $rows[$weight['widget']['weight']] = array($profile->content[$field]['#title'], $value[0]['#markup']);
      }
    }
    ksort($rows);
    
    $profile->content = array(0 => array('#markup' => theme('table', array('header' => $header, 'rows' => $rows, 'attributes' => $attributes))));
  }
}